name: Tag with GitVersion

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'terraform-docs.yaml'
      - 'gitversion.yaml'
  workflow_dispatch:

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all the history for GitVersion

      - name: Tag with GitVersion
        id: gitversion
        uses: michielvha/gitversion-tag-action@main
        with:
          configFilePath: 'gitversion.yaml'